config/routes.rb
Rails.application.routes.draw do
  namespace :beheren do
    resources :categories
    resources :articles
    resources :sessions, only: [:new, :create]
    root to: "articles#index"
  end
  resources :articles, only: [:index]
  root to: "articles#index"
  get "/artikel/:titel", to: "articles#show", as: "article"
  get "/404", to: "articles#index"
  get "/500", to: "articles#index"
  get "/:page", to: "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category

  validates :category_id, presence: true
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  protected

  def authorize
    raise StandardError.new unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_categories, obly: [:index, :show]

  def index
    @article = Article.last
  end

  def show
    @article = Article.find_by(title: params[:titel].gsub(/-/, " "))  
  end

  private
  def get_categories
    @categories = Category.all
  end
end

app/controllers/beheren/articles_controller.rb
class Beheren::ArticlesController < ApplicationController
  before_action :authorize
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to beheren_articles_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to beheren_articles_path, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to beheren_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :category_id)
    end
end

app/controllers/beheren/categories_controller.rb
class Beheren::CategoriesController < ApplicationController
  before_action :authorize
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to beheren_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to beheren_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to beheren_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/beheren/sessions_controller.rb
class Beheren::SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :get_categories, obly: [:show]

  def show
    render template: "pages/#{params[:page]}"
  end

  private
  def get_categories
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/index.haml
%h2= @article.title
%div= @article.description

app/views/articles/show.haml
%h2= @article.title
%div= @article.description.html_safe

app/views/beheren/articles/_form.haml
= f.input :category_id, collection: Category.pluck(:name, :id)
= f.input :title
= f.input :description, input_html: {class: "tinymce"}
= f.submit

app/views/beheren/articles/edit.haml
<h1>Editing Article</h1>

= simple_form_for @article, url: beheren_article_path(@article) do |f|
  = render "form", f: f

= link_to 'Back', beheren_articles_path

app/views/beheren/articles/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Categories', beheren_categories_path %>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= link_to 'Edit', edit_beheren_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_beheren_article_path %>

app/views/beheren/articles/new.haml
<h1>New Article</h1>

= simple_form_for @article, url: beheren_articles_path do |f|
  = render "form", f: f

= link_to 'Back', beheren_articles_path

app/views/beheren/categories/_form.haml
= f.input :name
= f.submit

app/views/beheren/categories/edit.haml
<h1>Editing Category</h1>

= simple_form_for @category, url: beheren_category_path(@category) do |f|
  = render "form", f: f

= link_to 'Back', beheren_categories_path

app/views/beheren/categories/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Articles', beheren_articles_path %>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %>
        <td><%= link_to 'Edit', edit_beheren_category_path(category) %></td>
        <td><%= link_to 'Destroy', [:beheren, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_beheren_category_path %>

app/views/beheren/categories/new.haml
<h1>New Category</h1>

= simple_form_for @category, url: beheren_categories_path do |f|
  = render "form", f: f

= link_to 'Back', beheren_categories_path

app/views/layouts/application.haml
<!DOCTYPE html>
%html
  %head
    %title Vrekkenclub
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container
      %header 
        %h1 Vrekkenclub
      - unless request.path.start_with?("/beheren")
        .row
          %ul.nav.nav-pills
            %li.nav-item
              = link_to "Home", "/", class: request.path == "/" ? "nav-link active" : "nav-link"
            %li.nav-item
              = link_to "Wie ben ik", "/wie-ben-ik", class: request.path != "/wie-ben-ik" ? "nav-link" : "nav-link active"
      .row
        - unless request.path.start_with?("/beheren")
          .col-2
            %ul.nav.flex-column
              - @categories.each do |category|
                %li.nav-item
                  = category.name
                  - category.articles.each do |article|
                    %ul.nav.flex-column.nav-pills
                      .row
                        .col-1 &nbsp;
                        .col-9
                          %li.nav-item
                            = link_to article.title, article_path(article.title.gsub(/ /, "-")), class: request.path.ends_with?(article.title.gsub(/ /, "-")) ? "nav-link active" : "nav-link"
            
        .col-8= yield

= tinymce

app/views/pages/wie-ben-ik.haml
%p Hallo, ik ben Jeroen. Mijn hobby is 'vrek zijn'.

%p Deze site staat vol met tips voor vrekken. Bespaar jij graag geld? Kies dan een van de categoriën en lees hoe jij een echte vrek kunt zijn.